Implement intersection of functional volume (fix #26)
Bisaloo/fundiversity pull request #30
Opened 2021-02-19 18:10 UTC by Rekyt

2021-02-23 20:39 UTC, Rekyt commented
For this PR I still need to:
1. add documentation in the introduction vignette,
2. add performance estimation in the performance vignette,
3. add a memoised version of fd_chull_intersect().

2021-03-02 14:39 UTC, Rekyt commented
@Bisaloo the PR is mostly ready for review.
One point that we have to inspect more closely is the risk of errors from `geometry::instersect()` it seems that many edge cases may fail and the documentation of this function clearly says that it sometimes have bad ouput.
So we should test the function on as many cases as possible and probably warn the users in the documentation.

2021-03-07 15:38 UTC, Bisaloo requested changes

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_chull_intersect.R
> +            min(r1[2], r2[2]))
```suggestion
    # Range of the overlap
    r3 <- c(max(traits1, traits2),
            min(traits1, traits2))
```

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_chull_intersect.R
> +    r_overlap <- diff(r3)
```suggestion
    r_overlap <- r3[2] - r3[1]
```

Better performance:

|expr               |  min|   lq|      mean| median|   uq|     max| neval|
|:------------------|----:|----:|---------:|------:|----:|-------:|-----:|
|{     1 - 2 }      |   84|  127|  161.1078|    137|  155| 4997253| 1e+06|
|{     diff(1, 2) } | 2214| 2407| 2760.8737|   2509| 2753| 9890056| 1e+06|

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_chull_intersect.R
> +    r_overlap <- ifelse(r_overlap < 0, NA_real_, r_overlap)
I don't understand how this case could happen. Could you add a comment why this check is necessary please?

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_chull_intersect.R
> +  return(geometry::intersectn(traits1, traits2, options = "FA"))
What about return only the `ch` element here? We would not have to create a "complex" nested list for the edge cases then

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +#' Intersection between functional volume of pairs of sites
The term functional volume is not super clear / intuitive for me. Is it a term that is present in the literature and easy to understand for people in the field? If so, we can leave it as is. Otherwise, it might be easier to understand if we re-use the term functional richness

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +#'
```suggestion
#'
#' @seealso [fd_fric()], [geometry::intersectn()]
#'
```

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +  all_site_comb <- tryCatch({
Can you add a comment explaining why the `tryCatch()` is necessary please?

2021-03-07 15:38 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +  self_intersection <- matrix(rep(rownames(sp_com), each = 2),
We know that the self intersection will be the itself so we should compute it why `convhulln()` instead of `intersectn()` because it's much more efficient:

|expr                 |      min|        lq|      mean|   median|        uq|      max| neval|
|:--------------------|--------:|---------:|---------:|--------:|---------:|--------:|-----:|
|intersectn(ps1, ps1) | 1312.947| 1370.2895| 1457.8260| 1395.387| 1431.6545| 6963.097|   100|
|convhulln(ps1)       |  183.773|  197.8175|  211.3715|  209.076|  224.3845|  272.437|   100|

2021-03-07 16:26 UTC, Rekyt commented on R/fd_fric_intersect.R
> +#' Intersection between functional volume of pairs of sites
If it's unclear to you than we should change it. Because even though it is straightfoward in functional ecology, if we want the package to target a broader group than we should use more commonly used terms. What alternative do you propose? Because "functional richness intersection" is not that common and does not it seem clearer to me. "Intersection of convex hulls"?

2021-03-07 16:28 UTC, Rekyt commented on R/fd_fric_intersect.R
> +  all_site_comb <- tryCatch({
the tryCatch was sort of a temporary. We need a little more testing here because the tryCatch() has to handle errors from `geometry::intersectn()` when it cannot find points in which the intersection is used. Have a look at `geometry::feasible.points()`.

2021-03-07 16:29 UTC, Rekyt commented on R/fd_fric_intersect.R
> +  self_intersection <- matrix(rep(rownames(sp_com), each = 2),
Indeed!

2021-03-08 10:16 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +#' Intersection between functional volume of pairs of sites
We can keep functional volume but add in parenthesis convex hull or something like this maybe?

2021-03-08 10:17 UTC, Bisaloo commented on R/fd_fric_intersect.R
> +  all_site_comb <- tryCatch({
But the `tryCatch()` here only wraps `combn()`, no?

2021-03-08 10:40 UTC, Rekyt commented on R/fd_chull_intersect.R
> +    r_overlap <- ifelse(r_overlap < 0, NA_real_, r_overlap)
fixed by fc3de5c

2021-03-08 10:40 UTC, Rekyt commented on R/fd_chull_intersect.R
> +  return(geometry::intersectn(traits1, traits2, options = "FA"))
fixed by c922b62

2021-03-08 10:45 UTC, Rekyt commented on R/fd_fric_intersect.R
> +  all_site_comb <- tryCatch({
Oops yes indeed! I was thinking about a different piece of code.
In this case it is to manage the case where there is a single row name.
Because `combn("a", 2)` returns an error.

2021-03-08 11:00 UTC, Rekyt commented on R/fd_fric_intersect.R
> +  self_intersection <- matrix(rep(rownames(sp_com), each = 2),
Fixed by 5581964

2021-03-08 11:01 UTC, Rekyt commented on R/fd_fric_intersect.R
> +  all_site_comb <- tryCatch({
Fixed by 5581964

2021-03-08 11:04 UTC, Rekyt commented on R/fd_fric_intersect.R
> +#' Intersection between functional volume of pairs of sites
Fixed by 8cd4668

2021-03-08 11:05 UTC, Rekyt reviewed
I normally solved all the issues you pointed at!

2021-03-08 11:29 UTC, Bisaloo approved these changes

2021-03-08 11:42 UTC, merged